AWSTemplateFormatVersion: "2010-09-09"
Description: StackSet to deploy Observability Access Manager Links to accounts

Conditions:
  AdditionalAccounts: !Not
    - !Equals
      - !Ref AccountFilterType
      - NONE

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - nonproduction
      - production
    Description: The environment to target for monitoring
  MonitoringAccountId:
    Type: String
  SinkIdentifier:
    Type: String
  TargetOrganizationalUnitIds:
    Type: List<String>
  AdditionalAccounts:
    Type: List<String>
    Default: ""
  AccountFilterType:
    Type: String
    Default: NONE
    AllowedValues:
      - INTERSECTION
      - DIFFERENCE
      - UNION
      - NONE
  Regions:
    Type: List<String>
    Default: eu-west-2
Resources:
  StackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      CallAs: DELEGATED_ADMIN
      Description: Observability managed stack, creating an Observability Access Manager Link to the central montoring account.
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 100
        MaxConcurrentPercentage: 100
      Parameters:
        - ParameterKey: MonitoringAccountId
          ParameterValue: !Ref MonitoringAccountId
        - ParameterKey: SinkIdentifier
          ParameterValue: !Ref SinkIdentifier
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - DeploymentTargets: !If
            - AdditionalAccounts
            - OrganizationalUnitIds: !Ref TargetOrganizationalUnitIds
              Accounts: !Ref AdditionalAccounts
              AccountFilterType: !Ref AccountFilterType
            - OrganizationalUnitIds: !Ref TargetOrganizationalUnitIds
          Regions: !Ref Regions
      StackSetName: !Ref AWS::StackName
      Tags:
        - Key: Name
          Value: observability-monitoring-link
        - Key: Product
          Value: GOV.UK One Login
        - Key: System
          Value: Observability
        - Key: Environment
          Value: !Ref Environment
      TemplateBody: |-
        AWSTemplateFormatVersion: 2010-09-09
        Description: Observability-managed stack, deploys a CloudWatch OAM Link for centralised monitoring.s

        Parameters:
          MonitoringAccountId:
            Type: String
          SinkIdentifier:
            Type: String

        Conditions:
          SkipMonitoringAccount: !Not
            - !Equals
              - !Ref AWS::AccountId
              - !Ref MonitoringAccountId

        Resources:
          Link:
            Type: AWS::Oam::Link
            Condition: SkipMonitoringAccount
            Properties:
              LabelTemplate: "$AccountName"
              ResourceTypes: 
                - "AWS::CloudWatch::Metric"
              SinkIdentifier: !Ref SinkIdentifier